//generated by https://app.quicktype.io/

export interface ProductListResponse {
  padelProducts: PadelProduct[];
}

export interface PadelProduct {
  id: number;
  nombre: string;
  descripcion: string;
  precio: number;
  stock: number;
  imagen: string;
  quantity: number; // Nuevo campo
  detalles: Detalles;
}

export interface Detalles {
  marca?: string;
  material?: string;
  peso?: string;
  nivel?: string;
  longitud?: string;
  'grosor del núcleo'?: string;
  equilibrio?: string;
  tipo?: string;
  'aprobación oficial'?: string;
  colores?: string[];
  'material de la carcasa'?: string;
  'resistencia al desgaste'?: string;
  duración?: string;
  entrenador?: string;
  ubicación?: string;
  disponibilidad?: string;
  'material del marco'?: string;
  'tamaño de la cabeza'?: string;
  'patrón de encordado'?: string;
  'material superior'?: string;
  suela?: string;
  'tallas disponibles'?: string[];
  incluye?: string[];
  'marcas de los accesorios'?: string[];
  calidad?: string;
  'colores disponibles'?: string[];
  tallas?: string[];
  'talla única'?: string;
  dimensiones?: string;
}
